site_name: ACM Foundations
docs_dir: './docs'
remote_branch: gh-pages
theme:
  name: material

  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon: assets/logo.png

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
nav:
    - Home: 'index.md'
    - Beginner:
      - 'C Programming Foundations-1': './Beginner-1/README.md'
      - 'C Programming Foundations-2': './Beginner-2/README.md'
      - 'C Programming Foundations-3': './Beginner-3/README.md'
      - 'C Programming Foundations-4': './Beginner-4/README.md'
    - Advanced:
      - 'Graph Theory': './Advanced-1/README.md'
      - 'Linked Lists, Stacks and Queues': './Advanced-2/README.md'
      - 'Hash Sets and Hash Maps': './Advanced-3/README.md'
      - 'Recursion and Dynamic Programming': './Advanced-4/README.md'
plugins:
  - search
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

extra_css:
  - assets/stylesheets/custom.css
